dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

dtb-$(CONFIG_SOC_EXYNOS8890) += exynos8890-maestro.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-smdk8895.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895_rev00.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895_d1_rev00.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895_d2_rev00.dtb
dtb-$(CONFIG_SOC_EMULATOR8895) += emulator8895-emulator8895.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895_d1_rev01.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-universal8895_d1_rev01_o_temp.dtb

dtb-$(CONFIG_MACH_EXYNOS8895_GREATLTE_EUR_OPEN) := \
	exynos8895-greatlte_eur_open_00.dtb \
	exynos8895-greatlte_eur_open_01.dtb \
	exynos8895-greatlte_eur_open_02.dtb \
	exynos8895-greatlte_eur_open_06.dtb \
	exynos8895-greatlte_eur_open_07.dtb \
#	exynos8895-greatlte_eur_open_03.dtb \
#	exynos8895-greatlte_eur_open_05.dtb

dtb-$(CONFIG_MACH_EXYNOS8895_GREATLTE_KOR) := \
	exynos8895-greatlte_kor_00.dtb \
	exynos8895-greatlte_kor_01.dtb \
	exynos8895-greatlte_kor_02.dtb \
	exynos8895-greatlte_kor_06.dtb \
#	exynos8895-greatlte_kor_03.dtb \
#	exynos8895-greatlte_kor_05.dtb

dtb-$(CONFIG_MACH_EXYNOS8895_DREAMLTE_EUR_OPEN) := \
	exynos8895-dreamlte_eur_open_00.dtb \
	exynos8895-dreamlte_eur_open_01.dtb \
	exynos8895-dreamlte_eur_open_02.dtb \
	exynos8895-dreamlte_eur_open_03.dtb \
	exynos8895-dreamlte_eur_open_04.dtb \
	exynos8895-dreamlte_eur_open_05.dtb \
	exynos8895-dreamlte_eur_open_07.dtb \
	exynos8895-dreamlte_eur_open_08.dtb \
	exynos8895-dreamlte_eur_open_09.dtb \
	exynos8895-dreamlte_eur_open_10.dtb

dtb-$(CONFIG_MACH_EXYNOS8895_DREAMLTE_KOR) := \
	exynos8895-dreamlte_kor_05.dtb \
	exynos8895-dreamlte_kor_07.dtb \
	exynos8895-dreamlte_kor_09.dtb \
	exynos8895-dreamlte_kor_10.dtb \
	exynos8895-dreamlte_kor_11.dtb

dtb-$(CONFIG_MACH_EXYNOS8895_DREAM2LTE_EUR_OPEN) := \
	exynos8895-dream2lte_eur_open_01.dtb \
	exynos8895-dream2lte_eur_open_02.dtb \
	exynos8895-dream2lte_eur_open_03.dtb \
	exynos8895-dream2lte_eur_open_04.dtb \
	exynos8895-dream2lte_eur_open_05.dtb \
	exynos8895-dream2lte_eur_open_06.dtb \
	exynos8895-dream2lte_eur_open_07.dtb \
	exynos8895-dream2lte_eur_open_08.dtb \
	exynos8895-dream2lte_eur_open_09.dtb \
	exynos8895-dream2lte_eur_open_10.dtb

dtb-$(CONFIG_MACH_EXYNOS8895_DREAM2LTE_KOR) := \
	exynos8895-dream2lte_kor_03.dtb \
	exynos8895-dream2lte_kor_04.dtb \
	exynos8895-dream2lte_kor_06.dtb \
	exynos8895-dream2lte_kor_07.dtb \
	exynos8895-dream2lte_kor_09.dtb \
	exynos8895-dream2lte_kor_10.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
